name: social_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Đa ngôn ngữ và địa phương hóa
  easy_localization: ^3.0.7+1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0 

  # Quản lý trạng thái
  flutter_riverpod: ^2.4.9
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.5
  uuid: ^4.5.1
  timeago: ^3.6.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_cache_manager: ^3.4.1
  connectivity_plus: ^5.0.2
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.0.1
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  flutter_image_compress: ^2.1.0
  photo_view: ^0.14.0
  video_player: ^2.9.3
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.13.1
  flutter_dotenv: ^5.1.0

  # Giao diện và thiết kế
  cupertino_icons: ^1.0.8
  animations: ^2.0.8
  rounded_loading_button: ^2.1.0
  animate_do: ^3.3.9
  scroll_bottom_navigation_bar: ^4.0.0

  # Xử lý hình ảnh và video
  image_picker: ^1.0.4
  image_cropper: ^9.0.0
  cached_network_image: ^3.4.1
  # flutter_sound_record: ^3.3.2
  # audioplayers: ^6.1.2

  # Tiện ích và công cụ
  date_format: ^2.0.9
  equatable: ^2.0.7
  fluttertoast: ^8.2.12
  flutter_holo_date_picker: ^2.0.0

  # Firebase
  lottie: ^3.3.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.4
  firebase_storage: ^12.4.4
  provider: ^6.1.2
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.4
  rxdart: ^0.27.7

  device_info_plus: ^11.3.3
  better_player_plus: ^1.0.8
  video_compress: ^3.1.4
  file_picker: ^9.2.1
  record: ^5.2.1
  flutter_sound: ^9.27.0
  just_audio: ^0.9.46
  audio_video_progress_bar: ^2.0.3
  mime: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/lottie/
