// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC-hpE8gzrcMslCsVrvKKKVBGFUVFfCPQ',
    appId: '1:1007646480719:web:1b08c84c412622f49f8d3a',
    messagingSenderId: '1007646480719',
    projectId: 'woven-plane-448115-r4',
    authDomain: 'woven-plane-448115-r4.firebaseapp.com',
    storageBucket: 'woven-plane-448115-r4.firebasestorage.app',
    measurementId: 'G-QZKM4D4V7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdaazXschJ51Rf_WQulEIYcj8lXIlp35A',
    appId: '1:1007646480719:android:42b4795ef1ab90b79f8d3a',
    messagingSenderId: '1007646480719',
    projectId: 'woven-plane-448115-r4',
    storageBucket: 'woven-plane-448115-r4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4uc06jiXRovOeoJkUfqHKIxbrGX99duU',
    appId: '1:1007646480719:ios:b36620eaa075c10d9f8d3a',
    messagingSenderId: '1007646480719',
    projectId: 'woven-plane-448115-r4',
    storageBucket: 'woven-plane-448115-r4.firebasestorage.app',
    iosBundleId: 'com.pvh.socialapp',
  );
}
